import { test, expect } from '@playwright/test';

test('3D atlas, geometry slider, independent sides, comparison, search, and saved shapes', async ({ page }) => {
  const errors: string[]=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto('./');
  await expect(page.locator('canvas')).toBeVisible({timeout:60000});
  await expect(page.locator('.viewer-status')).toHaveCount(0,{timeout:60000});
  await expect(page.getByRole('heading',{name:'Lateral deltoid',exact:true})).toBeVisible();
  await page.screenshot({path:'screenshots/desktop.png',fullPage:true});
  const canvas=page.locator('canvas');
  const reference=await canvas.screenshot();
  const slider=page.getByRole('slider');
  await slider.focus();
  await slider.press('End');
  await expect(page.locator('output')).toHaveText('10.00×');
  await page.waitForTimeout(300);
  const expanded=await canvas.screenshot();
  expect(expanded.equals(reference)).toBe(false);
  await page.getByRole('button',{name:'L',exact:true}).click();
  await slider.focus();await slider.press('Home');
  await expect(page.locator('output')).toHaveText('0.25×');
  await page.getByRole('button',{name:'R',exact:true}).click();
  await expect(page.locator('output')).toHaveText('10.00×');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.getByRole('button',{name:'L',exact:true}).click();
  await expect(page.locator('output')).toHaveText('10.00×');
  await page.getByRole('button',{name:'Both',exact:true}).click();
  const exact=page.getByRole('spinbutton',{name:'Exact multiplier'});
  await exact.fill('3.25');await exact.press('Enter');
  await expect(page.locator('output')).toHaveText('3.25×');
  await exact.fill('8');await exact.press('Escape');
  await expect(page.locator('output')).toHaveText('3.25×');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await expect(page.locator('output')).toHaveText('10.00×');
  await page.getByRole('button',{name:'1.50×',exact:true}).click();
  await page.getByRole('button',{name:'Physique',exact:true}).click();
  await page.waitForTimeout(300);
  await page.screenshot({path:'screenshots/physique.png',fullPage:true});
  await page.getByRole('button',{name:'Compare',exact:true}).click();
  await expect(page.locator('.comparison-labels')).toBeVisible();
  await page.waitForTimeout(700);
  await page.screenshot({path:'screenshots/compare.png',fullPage:true});
  await page.getByRole('button',{name:'Compare',exact:true}).click();
  await page.getByRole('button',{name:'Anatomy',exact:true}).click();
  await page.getByRole('textbox',{name:'Search muscles'}).fill('lumbrical');
  await expect(page.locator('.muscle-row')).not.toHaveCount(0);
  const small=page.locator('.muscle-row').first();
  await small.click();
  await page.getByRole('button',{name:'Isolate',exact:true}).click();
  await expect(page.getByRole('button',{name:'Isolate',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.waitForTimeout(600);
  await page.screenshot({path:'screenshots/small-muscle.png',fullPage:true});
  await page.getByRole('button',{name:'Isolate',exact:true}).click();
  await page.getByRole('button',{name:'Fit whole body'}).click();
  await page.getByRole('button',{name:'See through',exact:true}).click();
  await expect(page.getByRole('button',{name:'See through',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.getByRole('button',{name:'See through',exact:true}).click();
  await expect(page.getByRole('button',{name:'Save shape'})).toHaveCount(0);
  const saved=await page.evaluate(()=>localStorage.getItem('form-physique-v1'));
  await page.getByRole('button',{name:'Reset all'}).click();
  await expect(page.locator('.nav-count')).toHaveText('0');
  await page.locator('input[type=file]').setInputFiles({name:'previous-shape.json',mimeType:'application/json',buffer:Buffer.from(saved!)});
  await expect(page.locator('.nav-count')).toHaveText('1');
  await page.reload();
  await expect(page.locator('.nav-count')).toHaveText('1');
  await page.getByRole('button',{name:'About the model'}).click();
  await expect(page.locator('dialog')).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.locator('dialog')).not.toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile layout fits the viewport and retains usable controls',async({page})=>{
  await page.setViewportSize({width:390,height:844});
  await page.goto('./');
  await expect(page.locator('canvas')).toBeVisible({timeout:60000});
  await expect(page.locator('.viewer-status')).toHaveCount(0,{timeout:60000});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'screenshots/mobile.png',fullPage:true});
  await page.getByRole('slider').scrollIntoViewIfNeeded();
  await page.getByRole('slider').focus();await page.getByRole('slider').press('End');
  await expect(page.locator('output')).toHaveText('10.00×');
  await page.getByRole('textbox',{name:'Search muscles'}).fill('soleus');
  await page.locator('.muscle-row').click();
  await expect(page.getByRole('heading',{name:'Soleus',exact:true})).toBeVisible();
  await page.setViewportSize({width:320,height:740});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
